#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    show-sql: true

#Data Source
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kameleoon_db
    username: postgres
    password: postgres
  #Hibernate
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true